# Generated by Django 6.0.2 on 2026-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('dress', 'Dresses'), ('makeup', 'Makeup'), ('grocery', 'Groceries'), ('furniture', 'Furniture'), ('toys', 'Toys')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
